name: checks
on:
  - push
  - pull_request
jobs:
  test:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: go test -v
